version = 3.10.7
runner.dialect = scala3

style = defaultWithAlign
align.preset = most
maxColumn = 160
rewrite.rules = [SortImports, RedundantBraces, RedundantParens]
docstrings.wrapMaxColumn = 80
docstrings.blankFirstLine = no
docstrings.style = SpaceAsterisk
align.arrowEnumeratorGenerator = false
trailingCommas = always
