package com.boombustgroup.amorfati.engine.flows

import com.boombustgroup.ledger.*

/** Mechanism IDs for audit trail. Each mechanism that emits flows gets a unique
  * ID. amor-fati specific — the ledger only sees MechanismId(Int).
  */
object FlowMechanism:
  val ZusContribution: MechanismId       = MechanismId(1)
  val ZusPension: MechanismId            = MechanismId(2)
  val ZusGovSubvention: MechanismId      = MechanismId(3)
  val NfzContribution: MechanismId       = MechanismId(4)
  val NfzSpending: MechanismId           = MechanismId(5)
  val NfzGovSubvention: MechanismId      = MechanismId(6)
  val PpkContribution: MechanismId       = MechanismId(7)
  val PpkBondPurchase: MechanismId       = MechanismId(8)
  // Earmarked funds
  val FpContribution: MechanismId        = MechanismId(9)
  val FpSpending: MechanismId            = MechanismId(10)
  val FpGovSubvention: MechanismId       = MechanismId(11)
  val PfronContribution: MechanismId     = MechanismId(12)
  val PfronSpending: MechanismId         = MechanismId(13)
  val PfronGovSubvention: MechanismId    = MechanismId(14)
  val FgspContribution: MechanismId      = MechanismId(15)
  val FgspSpending: MechanismId          = MechanismId(16)
  val FgspGovSubvention: MechanismId     = MechanismId(17)
  // JST
  val JstRevenue: MechanismId            = MechanismId(18)
  val JstSpending: MechanismId           = MechanismId(19)
  // Government budget
  val GovTaxRevenue: MechanismId         = MechanismId(20)
  val GovPurchases: MechanismId          = MechanismId(21)
  val GovDebtService: MechanismId        = MechanismId(22)
  val GovCapitalInvestment: MechanismId  = MechanismId(23)
  val GovUnempBenefit: MechanismId       = MechanismId(24)
  val GovSocialTransfer: MechanismId     = MechanismId(25)
  val GovEuCofin: MechanismId            = MechanismId(26)
  // Insurance
  val InsLifePremium: MechanismId        = MechanismId(27)
  val InsNonLifePremium: MechanismId     = MechanismId(28)
  val InsLifeClaim: MechanismId          = MechanismId(29)
  val InsNonLifeClaim: MechanismId       = MechanismId(30)
  val InsInvestmentIncome: MechanismId   = MechanismId(31)
  // Household
  val HhConsumption: MechanismId         = MechanismId(32)
  val HhRent: MechanismId                = MechanismId(33)
  val HhPit: MechanismId                 = MechanismId(34)
  val HhDebtService: MechanismId         = MechanismId(35)
  val HhDepositInterest: MechanismId     = MechanismId(36)
  val HhRemittance: MechanismId          = MechanismId(37)
  val HhCcOrigination: MechanismId       = MechanismId(38)
  val HhCcDebtService: MechanismId       = MechanismId(39)
  val HhCcDefault: MechanismId           = MechanismId(40)
  // Firm
  val FirmWages: MechanismId             = MechanismId(41)
  val FirmCit: MechanismId               = MechanismId(42)
  val FirmLoanRepayment: MechanismId     = MechanismId(43)
  val FirmNewLoan: MechanismId           = MechanismId(44)
  val FirmInterestPaid: MechanismId      = MechanismId(45)
  val FirmCapex: MechanismId             = MechanismId(46)
  val FirmEquityIssuance: MechanismId    = MechanismId(47)
  val FirmBondIssuance: MechanismId      = MechanismId(48)
  val FirmIoPayment: MechanismId         = MechanismId(49)
  val FirmNplDefault: MechanismId        = MechanismId(50)
  val FirmProfitShifting: MechanismId    = MechanismId(51)
  val FirmFdiRepatriation: MechanismId   = MechanismId(52)
  val FirmGrossInvestment: MechanismId   = MechanismId(53)
  // Equity market (GPW)
  val EquityDomDividend: MechanismId     = MechanismId(54)
  val EquityForDividend: MechanismId     = MechanismId(55)
  val EquityDividendTax: MechanismId     = MechanismId(56)
  val EquityIssuance: MechanismId        = MechanismId(57)
  // Corporate bonds
  val CorpBondCoupon: MechanismId        = MechanismId(58)
  val CorpBondDefault: MechanismId       = MechanismId(59)
  val CorpBondIssuance: MechanismId      = MechanismId(60)
  val CorpBondAmortization: MechanismId  = MechanismId(61)
  // Housing / mortgages
  val MortgageOrigination: MechanismId   = MechanismId(62)
  val MortgageRepayment: MechanismId     = MechanismId(63)
  val MortgageInterest: MechanismId      = MechanismId(64)
  val MortgageDefault: MechanismId       = MechanismId(65)
  // Open economy / BoP
  val TradeExports: MechanismId          = MechanismId(66)
  val TradeImports: MechanismId          = MechanismId(67)
  val TourismExport: MechanismId         = MechanismId(68)
  val TourismImport: MechanismId         = MechanismId(69)
  val Fdi: MechanismId                   = MechanismId(70)
  val PortfolioFlow: MechanismId         = MechanismId(71)
  val PrimaryIncome: MechanismId         = MechanismId(72)
  val EuFunds: MechanismId               = MechanismId(73)
  val DiasporaInflow: MechanismId        = MechanismId(74)
  val CapitalFlight: MechanismId         = MechanismId(75)
  // Banking P&L
  val BankFirmInterest: MechanismId      = MechanismId(76)
  val BankGovBondIncome: MechanismId     = MechanismId(77)
  val BankNplLoss: MechanismId           = MechanismId(78)
  val BankMortgageNplLoss: MechanismId   = MechanismId(79)
  val BankCcNplLoss: MechanismId         = MechanismId(80)
  val BankCorpBondLoss: MechanismId      = MechanismId(81)
  val BankBfgLevy: MechanismId           = MechanismId(82)
  val BankUnrealizedLoss: MechanismId    = MechanismId(83)
  val BankReserveInterest: MechanismId   = MechanismId(84)
  val BankStandingFacility: MechanismId  = MechanismId(85)
  val BankInterbankInterest: MechanismId = MechanismId(86)
  val BankBailIn: MechanismId            = MechanismId(87)
  val BankNbpRemittance: MechanismId     = MechanismId(88)
  val EquityGovDividend: MechanismId     = MechanismId(89)
